// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Murat.API.Data;

namespace Murat.API.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Murat.API.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 2, 26, 15, 35, 29, 220, DateTimeKind.Local).AddTicks(248),
                            Name = "Bilgisayar",
                            Price = 15000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 2, 26, 15, 35, 29, 220, DateTimeKind.Local).AddTicks(8074),
                            Name = "Telefon",
                            Price = 18000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 2, 26, 15, 35, 29, 220, DateTimeKind.Local).AddTicks(8090),
                            Name = "Klavye",
                            Price = 100m,
                            Stock = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
